header_text:
  value: "<p class=\"text-align-center\"><strong>Always Players, Always a game</strong><br />\r\nBad beat &amp; Kickback draw /&nbsp;&nbsp;up to $200 to be won in cash giveaway at the start of the game (must be <a href=\"https://playersinc.ca/reserve\">reserved</a>)<br />\r\n<a href=\"tel:(647) 549-2036\">(647) 549-2036</a>, call (text only until we are open - we don't see them after)</p>\r\n"
  format: full_html
bg_color: '#fffacd'
operating_hours:
  value: "<p class=\"text-align-center\">Club opens 30 mins before start time<br />\r\nMonday - Thursday:&nbsp; 7 p.m. - 3 a.m.<br />\r\nFriday: 7 p.m. - 4 a.m.<br />\r\nSaturday (Tournament): 1 p.m. - 4 p.m.<br />\r\nSaturday (Cash): 4 p.m. - 4 a.m.<br />\r\nSunday: 4 p.m. - 3 a.m.</p>\r\n"
  format: full_html
