header_text:
  value: "<p><span style=\"color:#ffffff;\"><strong><span style=\"font-size:22px;\">ALWAYS PLAYERS ALWAYS A GAME - BAD BEAT OVER $ 22000 - 647-549-2036 OPEN EVERYDAY </span></strong></span></p>\r\n"
  format: full_html
bg_color: '#808080'
